- arguments:
    - -XDataKinds
    - -XDeriveGeneric
    - -XDuplicateRecordFields
    - -XFlexibleContexts
    - -XTypeApplications
    - -XDeriveFunctor
    - -XDeriveFoldable
    - -XDeriveTraversable
    - -XTypeOperators
    - -XApplicativeDo
    - -XViewPatterns
    - -XLambdaCase
    - -XGeneralizedNewtypeDeriving
    - -XTypeFamilies
    - -XScopedTypeVariables
    - -XRankNTypes
    - -XFlexibleInstances
    - -XDeriveDataTypeable
    - -XQuasiQuotes
    - -XTemplateHaskell
    - -XConstraintKinds
    - -XUndecidableInstances
    - -XMultiParamTypeClasses
    - -XKindSignatures
    - -XFunctionalDependencies
    - -XDataKinds
    - -XGADTs
    - -XStandaloneDeriving
    - -XViewPatterns
    - -XCPP
    - -XPartialTypeSignatures
    - -XPolyKinds
    - -XQuantifiedConstraints
    - -XDerivingVia
