version: 2
jobs:
  build:
    docker:
      - image: chewie123/ubuntu-z3:16.04_4.8.5_stack

    steps:
      - checkout

      - restore_cache:
          name: restore cached dependencies
          keys:
            - fuzzi-model-{{ checksum "stack.yaml" }}-{{ checksum "fuzzi-model.cabal" }}
            - fuzzi-model-{{ checksum "stack.yaml" }}

      - run:
          name: Build and Test
          command: stack test

      - save_cache:
          name: cache dependencies
          key: fuzzi-model-{{ checksum "stack.yaml" }}-{{ checksum "fuzzi-model.cabal" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
