name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run brew update
      run: brew update
    - name: Install z3 HEAD
      run: brew install z3 --HEAD
    - name: Install stack
      run: curl -sSL https://get.haskellstack.org/ | sh
    - name: Run stack test
      run: stack test
